const kindnessButton = document.getElementById('kindnessButton');
const kindnessResult = document.getElementById('kindnessResult');

const kindnessIdeas = [
    "😊 Leave a positive note for someone to find.",
    "🐾 Volunteer at an animal shelter.",
    "📚 Donate books you no longer read.",
    "🍪 Bake cookies and share them with your neighbors.",
    "🤗 Compliment a stranger.",
    "🌸 Send a heartfelt message to a friend.",
    "💌 Write a letter to someone you appreciate.",
    "🎁 Surprise someone with a small gift.",
    "🌼 Plant a tree or flowers in your community.",
    "👐 Help a neighbor with their groceries.",
    "🌞 Offer to babysit for a friend.",
    "🎨 Share your art with someone who would appreciate it.",
    "📝 Write a poem and share it online.",
    "🕊️ Release a balloon with a positive message.",
    "💖 Send a care package to a family member.",
    "🍽️ Treat a friend to lunch.",
    "📦 Help someone move or pack.",
    "🎧 Share your favorite music with someone.",
    "👩‍🍳 Cook a meal for a neighbor in need.",
    "📞 Call someone you haven't spoken to in a while.",
    "🌻 Create a small garden in your community.",
    "🌙 Leave a thoughtful comment on someone's social media.",
    "🎈 Organize a small gathering for friends.",
    "📷 Take a photo of a beautiful moment and share it.",
    "🤝 Offer to help a coworker with their tasks.",
    "🎤 Sing your heart out at a karaoke night with friends.",
    "✉️ Send a postcard to a friend in another city.",
    "🖍️ Donate art supplies to a local school.",
    "📅 Organize a community clean-up day.",
    "🎬 Share an inspiring movie recommendation.",
    "🤲 Give someone a heartfelt hug.",
    "🍀 Share your good luck charms with others.",
    "🌍 Start a recycling initiative in your neighborhood.",
    "🎣 Take a friend fishing for a day of relaxation.",
    "🌼 Make homemade cards for residents in a nursing home.",
    "🥤 Offer to buy a drink for the person behind you in line.",
    "🚗 Give a friend a ride when they need it.",
    "📜 Create a kindness jar and fill it with positive affirmations.",
    "📅 Make a plan to regularly check in on a friend.",
    "👥 Help someone find a job by referring them.",
    "🎡 Take someone to an amusement park for a day of fun.",
    "📊 Help a student with their homework.",
    "🌈 Share your favorite recipes with friends.",
    "🧸 Donate toys to a children's hospital.",
    "🎤 Encourage someone to pursue their dreams.",
    "🚶‍♂️ Go for a walk with someone who needs company.",
    "🎁 Make a donation to a charity of your choice.",
    "💞 Be a listening ear for someone going through a tough time.",
    "📚 Start a book club with friends.",
    "🖼️ Frame a piece of art and gift it to someone.",
    "🤳 Take a friend out for a fun day of photography.",
    "🎶 Create a playlist of uplifting songs for someone.",
    "📅 Organize a virtual game night with friends.",
    "💌 Send a handwritten thank-you note.",
    "🥳 Throw a small celebration for someone’s achievement.",
    "🌟 Give someone a compliment that you truly mean.",
    "🏆 Nominate someone for an award or recognition.",
    "🏞️ Plan a picnic at a local park.",
    "🐕 Offer to walk a neighbor's dog.",
    "🔍 Help a friend find a lost item.",
    "👩‍🏫 Offer to tutor someone in a subject you're good at.",
    "📖 Read to children at a local library or school.",
    "🥦 Share healthy recipes with friends.",
    "🍂 Create and share a gratitude list.",
    "📅 Volunteer for a local charity event.",
    "🏰 Plan a themed movie night at home.",
    "🎉 Celebrate small wins with friends.",
    "🧙‍♂️ Share a random act of kindness story online.",
    "🧩 Organize a puzzle night with friends.",
    "🌈 Leave encouraging sticky notes in public places.",
    "🌌 Spend time stargazing with someone.",
    "🎤 Encourage someone to express their creativity.",
    "📜 Share a quote that inspires you.",
    "🛒 Help someone with their grocery shopping.",
    "🥇 Send a virtual high-five to someone who needs encouragement.",
    "🖌️ Offer to paint a room for someone who needs help.",
    "📅 Create a monthly kindness challenge with friends.",
    "🍀 Share a plant cutting with a friend.",
    "📣 Promote a friend's small business on social media.",
    "🚴‍♂️ Take a friend on a bike ride.",
    "🎨 Host a craft night with friends.",
    "🏕️ Plan a camping trip for friends.",
    "🤹‍♀️ Share a skill with someone who wants to learn.",
    "📧 Reach out to someone you admire and share your appreciation.",
    "🎶 Attend a local concert or event with someone.",
    "🥘 Cook a meal together with a friend.",
    "📜 Write a list of things you're grateful for.",
    "🌟 Share your expertise by giving a talk or workshop.",
    "🖊️ Write a letter to your future self.",
    "🗳️ Encourage friends to vote in upcoming elections.",
    "💪 Offer to help someone with their fitness goals.",
    "🚀 Plan a fun adventure with friends.",
    "🏖️ Share a favorite beach spot with someone.",
    "🎂 Bake a cake and share it with friends.",
    "🧘‍♀️ Invite someone to join you for a yoga class.",
    "🚪 Hold the door open for someone.",
    "🕊️ Donate to a cause that matters to you.",
    "🎣 Take someone fishing for the first time.",
    "🏠 Host a game night at your place.",
    "🐦 Feed the birds in your local park.",
    "🍏 Share fresh fruits or vegetables from your garden.",
    "🖥️ Help a friend set up their computer.",
    "🎊 Share a funny story to lighten someone's mood.",
    "🤗 Invite someone who is new in town to join you for coffee.",
    "🥩 Host a barbecue and invite neighbors over.",
    "🌳 Organize a tree-planting event in your community.",
    "📩 Start a pen pal exchange with someone.",
    "🌾 Make a nature collage with leaves and flowers.",
    "🚦 Let someone merge in front of you in traffic.",
    "🏞️ Take a friend for a hike in nature.",
    "🏊‍♀️ Invite someone for a swim on a hot day.",
    "🍵 Brew a cup of tea for someone and sit down to chat.",
    "🌟 Leave a generous tip for your server.",
    "🎈 Organize a small surprise party for a friend.",
    "🧦 Donate socks to a local homeless shelter.",
    "🏌️ Take a friend golfing for the day.",
    "🏙️ Explore a new part of town with someone.",
    "🎤 Participate in a community talent show.",
    "📖 Gift a favorite book to someone.",
    "🌍 Start a neighborhood book exchange.",
    "🌈 Create colorful art to brighten someone's day.",
    "👩‍🎤 Share your musical talents with someone.",
    "👨‍🎨 Offer to help a friend with a DIY project.",
    "🍓 Make and share a smoothie with a friend.",
    "🎨 Share your favorite art supplies with someone new.",
    "🌈 Create a positive vision board with a friend.",
    "🎯 Set a kindness goal for the week and share it with others.",
    "🚴‍♀️ Join a friend for a cycling adventure.",
    "🌅 Go for a sunrise walk with someone.",
    "🌵 Send a small succulent as a gift.",
    "🥯 Share your favorite bagel shop with a friend.",
    "🌞 Create a gratitude wall in your home.",
    "🎼 Play music for neighbors to enjoy.",
    "🏆 Celebrate someone’s achievements publicly.",
    "🎪 Attend a local fair or festival together.",
    "🎭 Take a friend to a theater performance.",
    "📸 Organize a photo walk in your city.",
    "🛀 Treat someone to a spa day at home.",
    "🖌️ Paint rocks with positive messages and leave them in your community.",
    "📽️ Host a movie marathon with snacks and drinks.",
    "🎮 Share a favorite video game with a friend.",
    "🚀 Support a friend's new project by promoting it.",
    "🎨 Make DIY crafts and give them as gifts.",
    "🏖️ Share a favorite beach read with someone.",
    "🌿 Teach someone how to care for houseplants.",
    "📚 Host a story time for kids in your neighborhood.",
    "🛍️ Offer to carry someone's shopping bags.",
    "🎧 Recommend a favorite podcast to a friend.",
    "💌 Create and share a kindness bingo card.",
    "🎉 Organize a community potluck.",
    "🚶‍♀️ Go for a stroll with a friend and catch up.",
    "🍨 Treat a friend to ice cream.",
    "🚐 Organize a carpool for your community.",
    "📅 Plan a monthly dinner party with friends.",
    "🌅 Take a scenic drive and enjoy the views.",
    "🏌️‍♂️ Plan a mini-golf outing with friends.",
    "📦 Help someone unpack after moving.",
    "💼 Offer to review a friend's resume.",
    "🌟 Create a vision board for community improvement.",
    "🗳️ Organize a voter registration drive.",
    "🌱 Teach someone how to start a garden.",
    "🧩 Send a puzzle to someone for a fun activity.",
    "📦 Put together care packages for essential workers.",
    "🌿 Host a plant swap with friends.",
    "🕯️ Make homemade candles and gift them.",
    "📆 Send a reminder for important dates.",
    "🎊 Encourage friends to join you for a new hobby.",
    "🛷 Take someone sledding in the winter.",
    "📸 Share travel tips with someone planning a trip.",
    "💤 Offer to watch someone's pet while they're away.",
    "👩‍🌾 Visit a local farm and support farmers.",
    "🎶 Write and share a song about kindness.",
    "🍴 Host a cooking night with friends.",
    "🏞️ Organize a nature cleanup with your community.",
    "🚴‍♂️ Take a bicycle ride to enjoy the fresh air.",
    "📖 Share your favorite childhood book with someone.",
    "🛋️ Help someone rearrange their living space.",
    "🍳 Cook breakfast for someone special.",
    "🎂 Bake a cake for a celebration.",
    "🧹 Help clean a public space.",
    "🎨 Create a community art project.",
    "🚚 Offer to help someone with errands.",
    "🤖 Share a helpful app with a friend.",
    "🌿 Send someone a bouquet of flowers.",
    "🌌 Stargaze and share your favorite constellations.",
    "👩‍👧 Spend time volunteering with children.",
    "🏆 Create a recognition program for local heroes.",
    "🎉 Throw a small celebration for your team's achievements.",
    "📚 Start a community library box.",
    "🚶‍♂️ Take a leisurely walk and explore your city.",
    "🌅 Share a sunset view with someone.",
    "💸 Offer financial advice to someone in need.",
    "🏡 Help a friend with home repairs.",
    "🛶 Go canoeing or kayaking with a friend.",
    "🌍 Participate in an environmental advocacy group.",
    "👩‍🍳 Host a cooking class for friends.",
    "🧩 Organize a puzzle swap.",
    "📩 Share inspirational quotes in your community.",
    "🎤 Create a community talent showcase.",
    "🍬 Hand out treats to children on Halloween.",
    "📝 Help someone with their writing.",
    "🌿 Encourage friends to go plant-based for a week.",
    "🏕️ Plan a camping trip with friends.",
    "🍉 Host a picnic in the park.",
    "🍩 Treat someone to donuts on a Friday morning.",
    "🍽️ Share a family recipe with a friend.",
    "🌈 Paint kindness messages on rocks and leave them around town.",
    "🤝 Offer to mentor someone in your field.",
    "👩‍🍳 Teach someone how to bake a special dish.",
    "📅 Organize a community wellness day.",
    "🏡 Host an open house for friends and family.",
    "🖊️ Write a letter to your future self.",
    "🧚 Create a fairy garden in your community.",
    "🎨 Offer free art classes in your neighborhood.",
    "📚 Create a reading corner for children.",
    "🎧 Make a guided meditation for someone.",
    "🎡 Attend a local festival and support vendors.",
    "🏖️ Share beach essentials with a friend.",
    "🛀 Create a DIY spa day at home.",
    "🌟 Leave uplifting messages in public spaces.",
    "🚀 Organize a neighborhood treasure hunt.",
    "👨‍🌾 Start a community garden project.",
    "🏆 Celebrate acts of kindness in your community.",
    "🌍 Advocate for a cause you're passionate about.",
    "🏞️ Organize a group hike with friends.",
    "🍳 Share breakfast recipes with friends.",
    "📆 Write positive affirmations for each day of the week.",
    "🎶 Share your favorite workout playlist with a friend.",
    "🌳 Organize a tree planting event.",
    "👩‍🎓 Help a student with college applications.",
    "🌈 Create colorful sidewalk chalk art with positive messages.",
    "🍽️ Share your cooking skills with someone who needs help.",
    "🌅 Plan a sunset watch party.",
    "📋 Create a bucket list with friends.",
    "🚴‍♂️ Organize a group bike ride.",
    "🤗 Send a virtual hug to someone.",
    "🧩 Organize a game swap with friends.",
    "📝 Start a community blog for sharing good news.",
    "💌 Mail a care package to someone far away.",
    "🍫 Treat someone to their favorite snack.",
    "🍎 Share healthy snacks with coworkers.",
    "🌊 Organize a beach cleanup day.",
    "🦋 Create a butterfly garden in your yard.",
    "🍪 Share homemade cookies with neighbors.",
    "📅 Create a kindness calendar and promote it.",
    "🏖️ Host a beach day for friends.",
    "🏕️ Invite friends for a camping weekend.",
    "🚀 Host a launch party for a friend's new venture.",
    "🍇 Share fresh produce with neighbors.",
    "🎨 Create a mural in your community.",
    "🎤 Encourage friends to share their talents.",
    "🚐 Organize a charity drive for local needs.",
    "🌟 Celebrate others' accomplishments publicly.",
    "📚 Lead a workshop on a topic you love.",
    "🎊 Create a local art show.",
    "🚵‍♀️ Plan a cycling trip to explore nearby trails.",
    "🎨 Craft with friends and share the results.",
    "🏖️ Host a beach bonfire and invite friends.",
    "🏡 Offer to help someone decorate their home.",
    "🍂 Share autumn activities with friends.",
    "🚢 Plan a group cruise for relaxation.",
    "🍳 Share cooking tips with someone.",
    "💞 Help a friend plan a special date.",
    "🎉 Start a community appreciation project.",
    "🎈 Celebrate a friend's birthday with a surprise.",
    "📖 Create a community storytelling night.",
    "🏡 Offer to house sit for someone.",
    "🎆 Attend a local fireworks show with friends.",
    "🍁 Organize a leaf raking day for the elderly.",
    "📅 Host a monthly potluck dinner.",
    "👩‍🌾 Share gardening tips with someone.",
    "🚴‍♂️ Lead a cycling class at a local gym.",
    "🖌️ Create a kindness mural with your community.",
    "🍯 Share homemade jams or preserves.",
    "🌻 Create a flower arrangement for a friend.",
    "📅 Share your calendar of local events.",
    "📷 Host a photography contest in your area.",
    "🎉 Organize a celebration for community helpers.",
    "🤝 Offer to help someone with tech issues.",
    "🚀 Start a group challenge for fitness goals.",
    "🌈 Share colorful artwork with children.",
    "📅 Plan a monthly outing with friends.",
    "📝 Host a writing workshop.",
    "🍇 Share healthy smoothie recipes.",
    "🎉 Organize a flash mob for a cause.",
    "🏞️ Lead a guided nature walk.",
    "🍽️ Share dinner recipes with friends.",
    "🧘‍♂️ Host a mindfulness session.",
    "🏖️ Plan a beach day for friends.",
    "🚐 Organize a road trip with friends.",
    "👩‍🏫 Offer tutoring for students.",
    "🏄‍♂️ Plan a surfing lesson with friends.",
    "🌺 Create a community flower garden.",
    "🍪 Share cookie recipes with neighbors.",
    "📦 Organize a donation drive.",
    "🍁 Share autumn crafts with friends.",
    "🏕️ Plan a camping weekend with friends.",
    "🍲 Share soup recipes with neighbors.",
    "📸 Capture moments of kindness on camera.",
    "🍣 Share sushi recipes with friends.",
    "🎤 Host a karaoke night.",
    "🖥️ Teach a friend how to use a new app.",
    "📚 Share interesting articles with friends.",
    "🎨 Organize an art exhibit in your community.",
    "🧹 Help clean a local park.",
    "🏆 Create a recognition wall for community members.",
    "🎆 Attend a local festival and celebrate together.",
    "🌈 Share rainbow-themed crafts.",
    "🍦 Treat a friend to ice cream.",
    "🎉 Celebrate achievements with a party.",
    "🏖️ Plan a beach cleanup day.",
    "🚴‍♂️ Lead a community bike ride.",
    "🌳 Share gardening tips with friends.",
    "🍞 Bake bread and share with neighbors.",
    "🌟 Encourage someone to pursue their dreams.",
    "🎊 Organize a holiday party for friends.",
    "📚 Create a community reading list.",
    "🎶 Share a favorite playlist with someone.",
    "🎉 Celebrate kindness in your community.",
    "🌈 Share colorful decorations with friends.",
    "💌 Write encouraging letters to friends.",
    "🎊 Host a potluck for your neighborhood.",
    "🚶‍♀️ Walk with a friend and catch up.",
    "🏖️ Plan a beach day for relaxation.",
    "🌸 Share floral arrangements with neighbors.",
    "🍂 Create an autumn craft workshop.",
    "🎉 Organize a celebration for local heroes.",
    "📦 Help someone with their moving day.",
    "🎨 Share your art with a friend.",
    "🏞️ Plan a hiking trip with friends.",
    "📅 Organize a community calendar.",
    "🌼 Share flower seeds with neighbors.",
    "🚴‍♀️ Host a cycling event for charity.",
    "🍰 Bake a cake for a friend's birthday.",
    "📝 Create a gratitude journal.",
    "🦋 Share butterfly-themed crafts.",
    "🎉 Celebrate milestones with friends.",
    "🏖️ Plan a beach bonfire night.",
    "📚 Start a community book club.",
    "🍏 Share healthy snacks with coworkers.",
    "🏕️ Organize a campout in your backyard.",
    "🎶 Host a music night with friends.",
    "🎤 Encourage friends to share their stories.",
    "🧹 Help clean a local school.",
    "📅 Plan a monthly dinner with friends.",
    "🌻 Create a flower arrangement for someone special.",
    "🎉 Celebrate kindness in everyday life.",
    "🏖️ Plan a beach day with friends.",
    "📦 Organize a donation drive for local charities.",
    "🌟 Share inspirational quotes with your community.",
    "🚴‍♂️ Lead a group bike ride for fitness.",
    "🎨 Offer to paint a room for a friend.",
    "📅 Create a kindness calendar for your neighborhood.",
    "🍳 Cook breakfast for a friend.",
    "🌈 Share positive affirmations with others.",
    "🎉 Celebrate achievements with friends.",
    "🛍️ Support a local business by shopping there.",
    "🏖️ Plan a beach clean-up day.",
    "🍪 Share cookies with coworkers.",
    "🎊 Organize a talent show for charity.",
    "🏞️ Plan a nature hike with friends.",
    "🖍️ Host a craft night for friends.",
    "🍣 Share sushi-making tips.",
    "🎉 Celebrate kindness in your community.",
    "🚴‍♀️ Organize a cycling trip for fun.",
    "📝 Help someone with their writing.",
    "🌼 Create a flower garden in your community.",
    "🏡 Offer to help with home repairs.",
    "🍴 Cook a special dinner for a friend.",
    "🌈 Share your favorite hobbies with someone.",
    "🗳️ Encourage others to vote in elections.",
    "🏕️ Plan a camping weekend with friends.",
    "📆 Host a game night for friends.",
    "🌳 Share gardening tips with neighbors.",
    "🎉 Organize a community potluck.",
    "🍵 Share your favorite tea with a friend.",
    "🎈 Celebrate birthdays with friends.",
    "🍽️ Cook dinner for a friend.",
    "🌍 Promote sustainable practices in your community.",
    "🎨 Create a community art project.",
    "🏆 Recognize acts of kindness in your area.",
    "🍧 Share your favorite dessert with friends.",
    "🎶 Host a music jam session.",
    "🏖️ Plan a beach outing with friends.",
    "🌻 Create a gratitude wall in your community.",
    "📦 Help someone pack for a move.",
    "🎉 Organize a community festival.",
    "🍕 Share your favorite pizza recipe.",
    "🎨 Teach a friend a new art technique.",
    "🌈 Share colorful crafts with children.",
    "📅 Plan a movie marathon with friends.",
    "🚴‍♂️ Lead a cycling class at the gym.",
    "🎉 Celebrate achievements with a party.",
    "🏞️ Plan a group hike with friends.",
    "🍞 Share homemade bread with neighbors.",
    "🎊 Organize a community event.",
    "🏖️ Plan a beach day with friends.",
    "🚗 Offer to drive someone to an appointment.",
    "🍳 Share your favorite breakfast recipes.",
    "📚 Start a reading group in your neighborhood.",
    "🎤 Host a talent show for kids.",
    "📝 Create a local newsletter.",
    "🎉 Celebrate kindness every day.",
    "🦋 Share butterfly crafts with kids.",
    "🍪 Bake cookies for your neighbors.",
    "🏖️ Plan a beach clean-up event.",
    "🍏 Share healthy recipes with friends.",
    "🎊 Organize a fun run for charity.",
    "🌼 Create a flower arrangement for someone special.",
    "📦 Help a friend unpack after a move.",
    "🌈 Share positivity on social media.",
    "🎉 Celebrate small victories with friends.",
    "📅 Plan a community block party.",
    "🏞️ Lead a nature walk for kids.",
    "🧙‍♀️ Share your favorite magical stories.",
    "🎶 Organize a community concert.",
    "🍞 Bake bread and share it with your neighbors.",
    "🏖️ Plan a beach day with friends.",
    "🎉 Celebrate milestones with your community.",
    "🌼 Share flowers with friends.",
    "🍵 Host a tea party for friends.",
    "📅 Organize a game night with family.",
    "🎉 Celebrate accomplishments with friends.",
    "🍂 Share fall crafts with kids.",
    "🚴‍♂️ Lead a cycling event for charity.",
    "🏡 Offer to help a friend with home improvements.",
    "🌈 Create a colorful mural in your community.",
    "🌻 Share garden tips with neighbors.",
    "🎨 Host an art show in your neighborhood.",
    "📖 Share inspiring books with others.",
    "🎊 Celebrate kindness with a community event.",
    "🚀 Support local artists by attending their shows.",
    "🍉 Share your favorite summer recipes.",
    "🌟 Recognize everyday heroes in your life.",
    "📸 Capture acts of kindness on camera.",
    "📝 Write letters to soldiers or veterans.",
    "🎉 Celebrate kindness in your community.",
    "🍦 Treat a friend to ice cream on a hot day.",
    "🏞️ Organize a group hike.",
    "🖌️ Share painting tips with someone.",
    "🎶 Host a jam session for music lovers.",
    "🚗 Offer to run errands for someone.",
    "🌼 Create a community garden project.",
    "📦 Help someone declutter their home.",
    "📝 Organize a writing workshop.",
    "🎉 Celebrate kindness in your life.",
    "🏖️ Plan a beach day for relaxation.",
    "🌸 Share homemade gifts with friends.",
    "🎊 Organize a community cleanup day.",
    "🌳 Plant trees in your neighborhood.",
    "📅 Host a monthly community gathering.",
    "🛍️ Support local businesses by shopping locally.",
    "🍪 Bake cookies and give them to friends.",
    "🏡 Offer to help someone organize their home.",
    "🎉 Celebrate birthdays with parties.",
    "🌟 Recognize acts of kindness in your area.",
    "🍞 Bake bread for neighbors.",
    "🎨 Share your artistic talents with others.",
    "🏞️ Plan a nature hike with friends.",
    "🍇 Share healthy snacks with your community.",
    "🌼 Organize a community flower planting day.",
    "📅 Host a monthly potluck dinner.",
    "🚴‍♀️ Lead a cycling class at the gym.",
    "🎉 Celebrate small wins with friends.",
    "🦋 Share butterfly crafts with children.",
    "🍵 Host a tea party for your friends.",
    "🎉 Celebrate kindness every day.",
    "🏖️ Plan a beach outing with friends.",
    "📦 Help someone with their moving day.",
    "🎉 Organize a community event.",
    "🍫 Share your favorite chocolate with friends.",
    "🌟 Share positivity on social media.",
    "🏡 Offer to help someone organize their home.",
    "🎊 Plan a surprise for a friend's birthday.",
    "📅 Organize a neighborhood meeting.",
    "🍽️ Share your favorite recipes with friends.",
    "🌈 Create a colorful art project.",
    "🎉 Celebrate milestones in your community.",
    "🏖️ Plan a beach clean-up day.",
    "🍉 Share summer recipes with friends.",
    "🚴‍♂️ Organize a fun run for charity.",
    "📦 Help someone with their home organization.",
    "🌼 Create a flower garden in your neighborhood.",
    "🎉 Celebrate achievements with a community event.",
    "🏞️ Plan a nature hike with friends.",
    "🖍️ Share art supplies with kids.",
    "🎤 Host a karaoke night.",
    "🏡 Offer to house sit for a friend.",
    "📦 Help someone pack for a move.",
    "🎉 Celebrate kindness with a community event.",
    "🍪 Bake cookies and share them with friends.",
    "🏖️ Plan a beach day for relaxation.",
    "🚗 Offer to drive someone to their destination.",
    "🍞 Bake bread and share with neighbors.",
    "🗳️ Encourage others to get involved in their community.",
    "🏕️ Plan a camping trip with friends.",
    "🍉 Share summer snacks with neighbors.",
    "🏆 Celebrate kindness in everyday life.",
    "🎉 Organize a community festival.",
    "🏖️ Plan a beach day with friends.",
    "🌼 Share flower seeds with neighbors.",
    "📚 Start a community book club.",
    "🍳 Share breakfast recipes with friends.",
    "🍫 Treat someone to their favorite dessert.",
    "🎉 Celebrate acts of kindness in your area.",
    "🚴‍♀️ Lead a community bike ride.",
    "🍁 Organize a fall festival.",
    "🎨 Create a community mural.",
    "🏞️ Plan a nature outing with friends.",
    "🌈 Share positivity with your community.",
    "🏖️ Plan a beach clean-up day.",
    "🍪 Share cookies with neighbors.",
    "🎉 Celebrate birthdays with friends.",
    "📅 Plan a monthly community gathering.",
    "🚶‍♀️ Walk with a friend and catch up.",
    "📝 Write letters to encourage others.",
    "🏕️ Organize a camping trip with friends.",
    "🏡 Help someone with their home repairs.",
    "🌼 Create a flower garden in your neighborhood.",
    "🍵 Share tea with friends.",
    "🎉 Celebrate achievements with a party.",
    "🌍 Promote sustainability in your community.",
    "🍽️ Share dinner recipes with friends.",
    "🚴‍♂️ Lead a cycling event for fun.",
    "🎊 Organize a community event.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach day for relaxation.",
    "🍰 Bake a cake for a celebration.",
    "🌈 Share colorful crafts with friends.",
    "🎉 Celebrate milestones with your community.",
    "🌿 Create a community garden.",
    "🏞️ Plan a group hike.",
    "🌸 Share homemade gifts with friends.",
    "🏖️ Plan a beach outing with friends.",
    "📅 Host a game night with family.",
    "🍏 Share healthy recipes with friends.",
    "🎉 Celebrate accomplishments with friends.",
    "🍪 Bake cookies for your neighbors.",
    "🌈 Share positivity in your community.",
    "🏆 Recognize acts of kindness in your area.",
    "🚗 Offer to run errands for someone.",
    "🏕️ Organize a camping trip with friends.",
    "📦 Help someone unpack after a move.",
    "🍉 Share summer recipes with neighbors.",
    "🎉 Celebrate kindness in everyday life.",
    "🌻 Create a flower arrangement for someone special.",
    "🎉 Celebrate birthdays with a party.",
    "🎊 Organize a community cleanup day.",
    "🏖️ Plan a beach day with friends.",
    "🍞 Bake bread and share it with neighbors.",
    "🎉 Celebrate kindness in your community.",
    "🍏 Share healthy snacks with coworkers.",
    "🏖️ Plan a beach outing for fun.",
    "📅 Host a monthly potluck dinner.",
    "🎉 Celebrate achievements with friends.",
    "🚴‍♂️ Lead a cycling class at the gym.",
    "🏞️ Plan a group hike with friends.",
    "🍉 Share summer recipes with your neighbors.",
    "🌈 Create a colorful mural in your community.",
    "🎊 Organize a community event.",
    "🌼 Share flower seeds with neighbors.",
    "🏕️ Plan a camping trip with friends.",
    "🎉 Celebrate small wins with your community.",
    "🍪 Bake cookies and share them with friends.",
    "🌈 Share positivity on social media.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate kindness in your community.",
    "🍳 Share your favorite breakfast recipes.",
    "📅 Organize a neighborhood meeting.",
    "🎊 Plan a surprise for a friend's birthday.",
    "📚 Start a community book club.",
    "🎉 Celebrate accomplishments with friends.",
    "🍽️ Share dinner recipes with your community.",
    "🍏 Share healthy recipes with friends.",
    "🍪 Bake cookies and give them to friends.",
    "📦 Help someone with their home organization.",
    "🌼 Create a flower garden in your neighborhood.",
    "🏆 Recognize acts of kindness in your area.",
    "🍽️ Cook a special dinner for a friend.",
    "🍞 Bake bread for neighbors.",
    "🏖️ Plan a beach outing with friends.",
    "🍕 Share your favorite pizza recipe.",
    "🌈 Create a colorful art project.",
    "📅 Host a monthly community gathering.",
    "🍦 Treat a friend to ice cream on a hot day.",
    "🎉 Celebrate achievements with your community.",
    "🏡 Offer to help someone organize their home.",
    "🌈 Share positive affirmations with others.",
    "🍪 Bake cookies and share with friends.",
    "📦 Help someone with their moving day.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate kindness every day.",
    "🌼 Create a flower garden in your neighborhood.",
    "🍽️ Share dinner recipes with friends.",
    "📚 Start a community reading group.",
    "🎊 Organize a community event.",
    "🍏 Share healthy snacks with coworkers.",
    "🏖️ Plan a beach outing with friends.",
    "🍪 Bake cookies and share with neighbors.",
    "🏕️ Organize a camping trip with friends.",
    "🍰 Bake a cake for a celebration.",
    "🎉 Celebrate milestones in your community.",
    "🚴‍♀️ Lead a cycling event for charity.",
    "🍉 Share summer recipes with friends.",
    "🎨 Create a community mural.",
    "🎊 Organize a community event.",
    "🏖️ Plan a beach outing with friends.",
    "🌼 Share flower seeds with neighbors.",
    "🏡 Help someone with their home repairs.",
    "🎉 Celebrate kindness in your community.",
    "📦 Help someone with their moving day.",
    "🏖️ Plan a beach day for relaxation.",
    "🌻 Create a flower arrangement for someone special.",
    "🍰 Bake a cake for a celebration.",
    "🎉 Celebrate achievements with your community.",
    "🍇 Share healthy snacks with coworkers.",
    "🎊 Organize a community event.",
    "🍉 Share summer recipes with friends.",
    "🌈 Create a colorful mural in your community.",
    "🏖️ Plan a beach outing with friends.",
    "🌼 Share flower seeds with neighbors.",
    "📦 Help someone pack for a move.",
    "🏆 Recognize acts of kindness in your area.",
    "🍽️ Cook a special dinner for a friend.",
    "🏕️ Plan a camping trip with friends.",
    "🍪 Bake cookies and share with neighbors.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate small wins with friends.",
    "🏡 Help someone with their home repairs.",
    "🎊 Organize a community event.",
    "🌈 Share positivity on social media.",
    "🌼 Create a flower garden in your neighborhood.",
    "🎉 Celebrate achievements with friends.",
    "🍽️ Share dinner recipes with friends.",
    "📅 Host a game night with family.",
    "🎊 Plan a surprise for a friend's birthday.",
    "🏖️ Plan a beach outing with friends.",
    "🌈 Create colorful decorations for a celebration.",
    "🌼 Share flower seeds with neighbors.",
    "🎊 Organize a community event.",
    "📦 Help someone with their moving day.",
    "🏡 Help someone with their home repairs.",
    "🍽️ Cook a special dinner for a friend.",
    "🎉 Celebrate small wins with friends.",
    "🏞️ Plan a group hike.",
    "🍪 Bake cookies and share with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🍅 Share healthy recipes with your community.",
    "📚 Start a community reading group.",
    "🎉 Celebrate kindness in everyday life.",
    "🏖️ Plan a beach day for relaxation.",
    "🍉 Share summer recipes with friends.",
    "🎊 Organize a community event.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate achievements with friends.",
    "📅 Host a monthly potluck dinner.",
    "🌼 Create a flower arrangement for someone special.",
    "🍽️ Share your favorite dinner recipes.",
    "🎉 Celebrate small wins with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🍪 Bake cookies and share them with neighbors.",
    "🌈 Create colorful decorations for a celebration.",
    "📦 Help someone with their moving day.",
    "🏖️ Plan a beach outing for fun.",
    "🎊 Organize a community event.",
    "🏆 Recognize acts of kindness in your area.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate kindness in your community.",
    "🍏 Share healthy snacks with coworkers.",
    "🍉 Share summer recipes with friends.",
    "🎉 Celebrate small wins with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🏖️ Plan a beach day for relaxation.",
    "🎊 Organize a community event.",
    "🌈 Create a colorful mural in your neighborhood.",
    "🎉 Celebrate achievements with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🍪 Bake cookies and share with neighbors.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate small wins with friends.",
    "📚 Start a community reading group.",
    "🍏 Share healthy snacks with coworkers.",
    "🎉 Celebrate kindness in your community.",
    "🏡 Help someone with their home repairs.",
    "🍉 Share summer recipes with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate achievements with your community.",
    "🌼 Create a flower garden in your neighborhood.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach outing with friends.",
    "🍳 Share your favorite breakfast recipes.",
    "🎊 Organize a community event.",
    "🎉 Celebrate small wins with friends.",
    "🍪 Bake cookies and share with neighbors.",
    "🌈 Create colorful decorations for a celebration.",
    "📚 Start a community book club.",
    "🏖️ Plan a beach day for relaxation.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate achievements with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🌼 Create a flower arrangement for someone special.",
    "🎉 Celebrate small wins with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🎊 Organize a community event.",
    "🍏 Share healthy snacks with coworkers.",
    "🏖️ Plan a beach outing for fun.",
    "🎉 Celebrate small wins with friends.",
    "📅 Host a game night with family.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate kindness in everyday life.",
    "🌼 Create a flower garden in your neighborhood.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate small wins with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach outing with friends.",
    "🌈 Create colorful decorations for a celebration.",
    "🏡 Help someone with their home repairs.",
    "🎊 Organize a community event.",
    "🎉 Celebrate achievements with friends.",
    "🍪 Bake cookies and share with neighbors.",
    "🏕️ Organize a camping trip with friends.",
    "🌼 Create a flower garden in your neighborhood.",
    "🎉 Celebrate small wins with friends.",
    "🏖️ Plan a beach day for relaxation.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate achievements with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🌼 Create a flower arrangement for someone special.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate small wins with friends.",
    "🍏 Share healthy snacks with coworkers.",
    "🏕️ Organize a camping trip with friends.",
    "🎊 Organize a community event.",
    "📦 Help someone pack for a move.",
    "🎉 Celebrate achievements with friends.",
    "🏖️ Plan a beach outing for fun.",
    "🌼 Create a flower garden in your neighborhood.",
    "🎊 Organize a community event.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate small wins with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "🍪 Bake cookies and share with neighbors.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate achievements with your community.",
    "🌈 Create colorful decorations for a celebration.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach outing with friends.",
    "🍏 Share healthy snacks with coworkers.",
    "🎉 Celebrate small wins with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🌼 Create a flower garden in your neighborhood.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate achievements with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate small wins with friends.",
    "🎊 Organize a community event.",
    "🏡 Help someone with their home repairs.",
    "🍏 Share healthy snacks with coworkers.",
    "🌼 Create a flower arrangement for someone special.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate achievements with friends.",
    "🏖️ Plan a beach outing for fun.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate small wins with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "🍪 Bake cookies and share with neighbors.",
    "🏖️ Plan a beach day for relaxation.",
    "🌈 Create colorful decorations for a celebration.",
    "📦 Help someone pack for a move.",
    "🏕️ Organize a camping trip with friends.",
    "🍏 Share healthy snacks with coworkers.",
    "🎉 Celebrate achievements with your community.",
    "🌼 Create a flower garden in your neighborhood.",
    "🎊 Organize a community event.",
    "🍅 Share healthy recipes with your community.",
    "🏖️ Plan a beach outing for fun.",
    "🎉 Celebrate small wins with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🍪 Bake cookies and share with neighbors.",
    "🌼 Create a flower arrangement for someone special.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate achievements with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach outing for fun.",
    "🎉 Celebrate small wins with friends.",
    "🎊 Organize a community event.",
    "🌈 Create colorful decorations for a celebration.",
    "🎉 Celebrate small wins with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🍅 Share healthy recipes with your community.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate achievements with your community.",
    "🍪 Bake cookies and share with neighbors.",
    "🏆 Recognize acts of kindness in your area.",
    "🎊 Organize a community event.",
    "🍏 Share healthy snacks with coworkers.",
    "🎉 Celebrate small wins with friends.",
    "🏕️ Organize a camping trip with friends.",
    "🍅 Share healthy recipes with your community.",
    "🏖️ Plan a beach outing for fun.",
    "🌼 Create a flower arrangement for someone special.",
    "📦 Help someone pack for a move.",
    "🎉 Celebrate achievements with friends.",
    "🏆 Recognize acts of kindness in your area.",
    "🏕️ Organize a camping trip with friends.",
    "🎊 Organize a community event.",
    "🍏 Share healthy snacks with coworkers.",
    "🍪 Bake cookies and share with neighbors.",
    "🏖️ Plan a beach day for relaxation.",
    "🎉 Celebrate small wins with friends.",
    "📦 Help someone pack for a move.",
    "🏆 Recognize acts of kindness in your area.",
    "🌈 Create colorful decorations for a celebration.",
    "🎉 Celebrate small wins with friends.",
    "🏖️ Plan a beach outing for fun.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate achievements with friends.",
    "🍅 Share healthy recipes with your community.",
    "🏆 Recognize acts of kindness in your area.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach day for relaxation.",
    "🎊 Organize a community event.",
    "🌼 Create a flower arrangement for someone special.",
    "🎉 Celebrate small wins with friends.",
    "🍪 Bake cookies and share with neighbors.",
    "🏕️ Organize a camping trip with friends.",
    "🏖️ Plan a beach outing for fun.",
    "🍅 Share healthy recipes with your community.",
    "🎉 Celebrate achievements with friends.",
    "📦 Help someone pack for a move.",
    "🏆 Recognize acts of kindness in your area.",
    "🌼 Create a flower garden in your neighborhood.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate small wins with friends.",
    "🍅 Share healthy recipes with your community.",
    "🏖️ Plan a beach day for relaxation.",
    "🏆 Recognize acts of kindness in your area.",
    "🎊 Organize a community event.",
    "🍪 Bake cookies and share with neighbors.",
    "🌈 Create colorful decorations for a celebration.",
    "🎉 Celebrate achievements with friends.",
    "🏖️ Plan a beach outing for fun.",
    "🍏 Share healthy snacks with coworkers.",
    "🏕️ Organize a camping trip with friends.",
    "🎉 Celebrate small wins with friends.",
    "📦 Help someone pack for a move.",
    "🏖️ Plan a beach day for relaxation.",
    "🎊 Organize a community event.",
];

kindnessButton.addEventListener('click', function() {
    const randomIndex = Math.floor(Math.random() * kindnessIdeas.length);
    kindnessResult.textContent = kindnessIdeas[randomIndex];
}); 